### ISSUE TITLE
Version 2.0

### ISSUE THREAD

**Issue by luisvinicius167** [luisvinicius167/riotux#14]
Working on new version of Riotux. Now, you can dispatch your actions and do something when the Store state was changed. Like this: 
```javascript
import {dispatch} from 'riotux'
dispatch('increment', 1).then( ( newState ) => {
  console.log(`The state was changed. Receive new data: ${newState.action} : ${newState.stateValue}`);
})
```

Inside your Action, you need return a Promise, and inside your promise you can do what you whant. Like this:

```javascript
import {setActions} from 'riotux'

setActions({
  increment: (state, n) => {
    return new Promise((resolve, reject) => {
     // your async function
      setTimeout(() => {
        let result = state.count += n;
        resolve(result);
      }, 2000)
    });
  }
});
```

And you can set your Store state with ```setState```. Your application state is just a simple Object.

```javascript
import {setState} from 'riotux'

setState({
  count: 0
})
```

You can see the new work here: [Branch new](https://github.com/luisvinicius167/riotux/tree/new)

I'm planning create a Riotux Dev Tools too. :)

Feedbaks are very welcome! Thanks!

**Comment by darklow** [comment]
Looks like you want to force me to finally learn ECMAScript, so far I have successfully avoided it.
I'll take a look, but first I need to understand your examples.

I had no issues so far with current version :) Except maybe few times I wish there would be a way to prevent calling update to components, because not all actions do required update in the end. For example you do some kind of server-side check and realise data hasn't been changed, so why call update. But is a small thing.

**Comment by luisvinicius167** [comment]
@darklow great! Yeah, shure! With this, you don't need update your component after called your action. You can do something, see: ``dispatch('actionName').then( data => { // do something with the data retorned of your action} )``.

**Comment by darklow** [comment]
Is it possible to use new version with JavaScript only?

**Comment by luisvinicius167** [comment]
@darklow Shure! You can just import the mockstate.min.js on your Browser, that will export the ```Mockstate``` Object, then you can use Mockstate.dispatch, Mockstate.setState...
